apiVersion: unikernel.serverless.io/v1alpha1
kind: ServerlessConfig
spec:
  services:
    - name: serverless-test
      serverlessTemplate: path:///home/lzuccarelli/Projects/rust-serverless-interface-template
      version: 0.1.1
      authors: 
        - lmzuccarelli luzuccar@redhat.com
        - mtroisi hello@marcotroisi.com
      description: "Simple demo of a unikernel serverless webservice"
      env:
        - name: LOG_LEVEL
          value: TRACE
        - name: SERVER_PORT
          value: 3030
        - name: IP
          value: "0.0.0.0"
     

